import type { Metadata } from "next";
import { catamaran, firaSans } from "./fonts";
import "@/css/globals.css";

import { cn } from "@/lib/utils";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const BackgroundOverlay = () => (
  <div
    id="background-overlay"
    className={cn(
      "before:pointer-events-none after:pointer-events-none before:content-[''] before:bg-[url('/static/images/green-dust-and-scratches.png')] before:bg-repeat",
      "before:absolute before:inset-0 before:opacity-30 before:z-[-1]",
      "after:content-[''] after:absolute after:inset-0 after:bg-gradient-to-t after:from-transparent after:to-green-800/5 after:z-[-1]",
    )}
  />
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${catamaran.variable} ${firaSans.variable} antialiased text-white`}
      >
        <div className="page-outer relative">
          <div className="page-inner min-h-screen flex flex-col">
            <BackgroundOverlay />
            <header />
            <main className="flex-1 flex justify-center flex-grow [&>div]:w-full">
              {children}
            </main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
